In [1]:
# 1) Install dependencies
!pip -q install -U transformers accelerate peft bitsandbytes sentencepiece huggingface_hub pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 70.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 83.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.1 which is incompatible.
db-dtypes 1.5.0 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.1 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.1 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.1 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.1 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.1 which is incompatible.

In [1]:
!pip install pandas==2.2.2

Collecting pandas==2.2.2
  Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 41.2 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 3.0.1
    Uninstalling pandas-3.0.1:
      Successfully uninstalled pandas-3.0.1
Successfully installed pandas-2.2.2

In [2]:
# 2) Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:

%cd /content
!rm -rf llama.cpp
!git clone https://github.com/ggerganov/llama.cpp.git
%cd /content/llama.cpp
!cmake -B build
!cmake --build build --config Release -j 2

/content
Cloning into 'llama.cpp'...
remote: Enumerating objects: 84565, done.
remote: Counting objects: 100% (158/158), done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 84565 (delta 96), reused 48 (delta 48), pack-reused 84407 (from 4)
Receiving objects: 100% (84565/84565), 332.82 MiB | 1.32 MiB/s, done.
Resolving deltas: 100% (60917/60917), done.
/content/llama.cpp
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE=Release
-- Found Git: /usr/bin/git (found version "2.34.1")
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- ggml version: 0.9.8
-- ggml commit:  512bba6ee
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.2")
-- Performing Test OPENSSL_VERSION_SUPPORTED
-- Performing Test OPENSSL_VERSION_SUPPORTED - Success
-- OpenSSL found: 3.0.2
-- Generating embedded license file for target: common
-- Configuring done (1.7s)
-- Generating done (0.5s)
-- Build files have been written to: /content/llama.cpp/build
[  1%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml.c.o
[  1%] Building CXX object common/CMakeFiles/build_info.dir/build-info.cpp.o
[  1%] Built target build_info
[  1%] Building CXX object vendor/cpp-httplib/CMakeFiles/cpp-httplib.dir/httplib.cpp.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml.cpp.o
[  1%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-alloc.c.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-backend.cpp.o
[  1%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-opt.cpp.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-threading.cpp.o
[  2%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-quants.c.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o
[  2%] Linking CXX shared library ../../bin/libggml-base.so
[  2%] Built target ggml-base
[  2%] Building C object examples/gguf-hash/CMakeFiles/sha256.dir/deps/sha256/sha256.c.o
[  2%] Built target sha256
[  3%] Building C object examples/gguf-hash/CMakeFiles/xxhash.dir/deps/xxhash/xxhash.c.o
[  3%] Built target xxhash
[  3%] Building C object examples/gguf-hash/CMakeFiles/sha1.dir/deps/sha1/sha1.c.o
[  3%] Built target sha1
[  3%] Building CXX object tools/mtmd/CMakeFiles/llama-llava-cli.dir/deprecation-warning.cpp.o
[  3%] Linking CXX executable ../../bin/llama-llava-cli
[  3%] Built target llama-llava-cli
[  3%] Building CXX object tools/mtmd/CMakeFiles/llama-gemma3-cli.dir/deprecation-warning.cpp.o
[  3%] Linking CXX executable ../../bin/llama-gemma3-cli
[  3%] Built target llama-gemma3-cli
[  4%] Building CXX object tools/mtmd/CMakeFiles/llama-minicpmv-cli.dir/deprecation-warning.cpp.o
[  4%] Linking CXX executable ../../bin/llama-minicpmv-cli
[  4%] Built target llama-minicpmv-cli
[  4%] Building CXX object tools/mtmd/CMakeFiles/llama-qwen2vl-cli.dir/deprecation-warning.cpp.o
[  4%] Linking CXX executable ../../bin/llama-qwen2vl-cli
[  4%] Built target llama-qwen2vl-cli
[  4%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ggml-cpu.c.o
[  5%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ggml-cpu.cpp.o
[  5%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/repack.cpp.o
[  5%] Linking CXX static library libcpp-httplib.a
[  5%] Built target cpp-httplib
[  5%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/hbm.cpp.o
[  5%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/quants.c.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/traits.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/amx/amx.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/amx/mmq.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/binary-ops.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/unary-ops.cpp.o
[  7%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/vec.cpp.o
[  7%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ops.cpp.o
[  7%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/llamafile/sgemm.cpp.o
[  7%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/arch/x86/quants.c.o
[  8%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/arch/x86/repack.cpp.o
[  8%] Linking CXX shared library ../../bin/libggml-cpu.so
[  8%] Built target ggml-cpu
[  8%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-backend-dl.cpp.o
[  8%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-backend-reg.cpp.o
[  8%] Linking CXX shared library ../../bin/libggml.so
[  8%] Built target ggml
[  8%] Building CXX object examples/gguf-hash/CMakeFiles/llama-gguf-hash.dir/gguf-hash.cpp.o
[  8%] Building CXX object src/CMakeFiles/llama.dir/llama.cpp.o
[  8%] Linking CXX executable ../../bin/llama-gguf-hash
[  8%] Built target llama-gguf-hash
[  9%] Building CXX object src/CMakeFiles/llama.dir/llama-adapter.cpp.o
[  9%] Building CXX object src/CMakeFiles/llama.dir/llama-arch.cpp.o
[ 10%] Building CXX object examples/gguf/CMakeFiles/llama-gguf.dir/gguf.cpp.o
[ 10%] Linking CXX executable ../../bin/llama-gguf
[ 10%] Built target llama-gguf
[ 10%] Building CXX object src/CMakeFiles/llama.dir/llama-batch.cpp.o
[ 10%] Building CXX object src/CMakeFiles/llama.dir/llama-chat.cpp.o
[ 11%] Building CXX object src/CMakeFiles/llama.dir/llama-context.cpp.o
[ 11%] Building CXX object src/CMakeFiles/llama.dir/llama-cparams.cpp.o
[ 11%] Building CXX object src/CMakeFiles/llama.dir/llama-grammar.cpp.o
[ 11%] Building CXX object src/CMakeFiles/llama.dir/llama-graph.cpp.o
[ 11%] Building CXX object src/CMakeFiles/llama.dir/llama-hparams.cpp.o
[ 12%] Building CXX object src/CMakeFiles/llama.dir/llama-impl.cpp.o
[ 12%] Building CXX object src/CMakeFiles/llama.dir/llama-io.cpp.o
[ 12%] Building CXX object src/CMakeFiles/llama.dir/llama-kv-cache.cpp.o
[ 12%] Building CXX object src/CMakeFiles/llama.dir/llama-kv-cache-iswa.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-memory.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-memory-hybrid.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-memory-hybrid-iswa.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-memory-recurrent.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-mmap.cpp.o
[ 14%] Building CXX object src/CMakeFiles/llama.dir/llama-model-loader.cpp.o
[ 14%] Building CXX object src/CMakeFiles/llama.dir/llama-model-saver.cpp.o
[ 14%] Building CXX object src/CMakeFiles/llama.dir/llama-model.cpp.o
[ 14%] Building CXX object src/CMakeFiles/llama.dir/llama-quant.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/llama-sampler.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/llama-vocab.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/unicode-data.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/unicode.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/models/afmoe.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/models/apertus.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/models/arcee.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/models/arctic.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/models/arwkv7.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/models/baichuan.cpp.o
[ 17%] Building CXX object src/CMakeFiles/llama.dir/models/bailingmoe.cpp.o
[ 17%] Building CXX object src/CMakeFiles/llama.dir/models/bailingmoe2.cpp.o
[ 17%] Building CXX object src/CMakeFiles/llama.dir/models/bert.cpp.o
[ 17%] Building CXX object src/CMakeFiles/llama.dir/models/bitnet.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/models/bloom.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/models/chameleon.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/models/chatglm.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/models/codeshell.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/models/cogvlm.cpp.o
[ 19%] Building CXX object src/CMakeFiles/llama.dir/models/cohere2-iswa.cpp.o
[ 19%] Building CXX object src/CMakeFiles/llama.dir/models/command-r.cpp.o
[ 19%] Building CXX object src/CMakeFiles/llama.dir/models/dbrx.cpp.o
[ 19%] Building CXX object src/CMakeFiles/llama.dir/models/deci.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/models/deepseek.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/models/deepseek2.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/models/delta-net-base.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/models/dots1.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/models/dream.cpp.o
[ 21%] Building CXX object src/CMakeFiles/llama.dir/models/ernie4-5-moe.cpp.o
[ 21%] Building CXX object src/CMakeFiles/llama.dir/models/ernie4-5.cpp.o
[ 21%] Building CXX object src/CMakeFiles/llama.dir/models/eurobert.cpp.o
[ 21%] Building CXX object src/CMakeFiles/llama.dir/models/exaone-moe.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/models/exaone.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/models/exaone4.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/models/falcon-h1.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/models/falcon.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/models/gemma-embedding.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/models/gemma.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/models/gemma2-iswa.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/models/gemma3.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/models/gemma3n-iswa.cpp.o
[ 24%] Building CXX object src/CMakeFiles/llama.dir/models/glm4-moe.cpp.o
[ 24%] Building CXX object src/CMakeFiles/llama.dir/models/glm4.cpp.o
[ 24%] Building CXX object src/CMakeFiles/llama.dir/models/gpt2.cpp.o
[ 24%] Building CXX object src/CMakeFiles/llama.dir/models/gptneox.cpp.o
[ 24%] Building CXX object src/CMakeFiles/llama.dir/models/granite-hybrid.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/granite.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/grok.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/grovemoe.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/hunyuan-dense.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/hunyuan-moe.cpp.o
[ 26%] Building CXX object src/CMakeFiles/llama.dir/models/internlm2.cpp.o
[ 26%] Building CXX object src/CMakeFiles/llama.dir/models/jais.cpp.o
[ 26%] Building CXX object src/CMakeFiles/llama.dir/models/jais2.cpp.o
[ 26%] Building CXX object src/CMakeFiles/llama.dir/models/jamba.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/kimi-linear.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/lfm2.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/llada-moe.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/llada.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/llama-iswa.cpp.o
[ 28%] Building CXX object src/CMakeFiles/llama.dir/models/llama.cpp.o
[ 28%] Building CXX object src/CMakeFiles/llama.dir/models/maincoder.cpp.o
[ 28%] Building CXX object src/CMakeFiles/llama.dir/models/mamba-base.cpp.o
[ 28%] Building CXX object src/CMakeFiles/llama.dir/models/mamba.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/mimo2-iswa.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/minicpm3.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/minimax-m2.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/mistral3.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/modern-bert.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/mpt.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/nemotron-h.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/nemotron.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/neo-bert.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/olmo.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/olmo2.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/olmoe.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/openai-moe-iswa.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/openelm.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/orion.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/paddleocr.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/pangu-embedded.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/phi2.cpp.o
[ 33%] Building CXX object src/CMakeFiles/llama.dir/models/phi3.cpp.o
[ 33%] Building CXX object src/CMakeFiles/llama.dir/models/plamo.cpp.o
[ 33%] Building CXX object src/CMakeFiles/llama.dir/models/plamo2.cpp.o
[ 33%] Building CXX object src/CMakeFiles/llama.dir/models/plamo3.cpp.o
[ 33%] Building CXX object src/CMakeFiles/llama.dir/models/plm.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/qwen.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/qwen2.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/qwen2moe.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/qwen2vl.cpp.o
[ 35%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3.cpp.o
[ 35%] Building CXX object src/CMakeFiles/llama.dir/models/qwen35.cpp.o
[ 35%] Building CXX object src/CMakeFiles/llama.dir/models/qwen35moe.cpp.o
[ 35%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3moe.cpp.o
[ 35%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3next.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3vl-moe.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3vl.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/refact.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/rnd1.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv6-base.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv6.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv6qwen2.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv7-base.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv7.cpp.o
[ 38%] Building CXX object src/CMakeFiles/llama.dir/models/seed-oss.cpp.o
[ 38%] Building CXX object src/CMakeFiles/llama.dir/models/smallthinker.cpp.o
[ 38%] Building CXX object src/CMakeFiles/llama.dir/models/smollm3.cpp.o
[ 38%] Building CXX object src/CMakeFiles/llama.dir/models/stablelm.cpp.o
[ 38%] Building CXX object src/CMakeFiles/llama.dir/models/starcoder.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/starcoder2.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/step35-iswa.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/t5-dec.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/t5-enc.cpp.o
[ 40%] Building CXX object src/CMakeFiles/llama.dir/models/wavtokenizer-dec.cpp.o
[ 40%] Building CXX object src/CMakeFiles/llama.dir/models/xverse.cpp.o
[ 40%] Linking CXX shared library ../bin/libllama.so
[ 40%] Built target llama
[ 41%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/mtmd.cpp.o
[ 41%] Building CXX object common/CMakeFiles/common.dir/arg.cpp.o
[ 41%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/mtmd-audio.cpp.o
[ 41%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/mtmd-helper.cpp.o
[ 41%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/clip.cpp.o
[ 41%] Building CXX object common/CMakeFiles/common.dir/chat-auto-parser-generator.cpp.o
[ 42%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/cogvlm.cpp.o
[ 42%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/conformer.cpp.o
[ 42%] Building CXX object common/CMakeFiles/common.dir/chat-auto-parser-helpers.cpp.o
[ 42%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/glm4v.cpp.o
[ 42%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/internvl.cpp.o
[ 42%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/kimivl.cpp.o
[ 43%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/kimik25.cpp.o
[ 44%] Building CXX object common/CMakeFiles/common.dir/chat-diff-analyzer.cpp.o
[ 44%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/nemotron-v2-vl.cpp.o
[ 44%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/llama4.cpp.o
[ 44%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/llava.cpp.o
[ 44%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/minicpmv.cpp.o
[ 45%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/paddleocr.cpp.o
[ 45%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/pixtral.cpp.o
[ 45%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/qwen2vl.cpp.o
[ 45%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/qwen3vl.cpp.o
[ 46%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/siglip.cpp.o
[ 46%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/whisper-enc.cpp.o
[ 46%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/mobilenetv5.cpp.o
[ 46%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/youtuvl.cpp.o
[ 46%] Building CXX object common/CMakeFiles/common.dir/chat-peg-parser.cpp.o
[ 46%] Linking CXX shared library ../../bin/libmtmd.so
[ 46%] Built target mtmd
[ 46%] Building CXX object common/CMakeFiles/common.dir/chat.cpp.o
[ 46%] Building C object tests/CMakeFiles/test-c.dir/test-c.c.o
[ 46%] Linking C executable ../bin/test-c
[ 46%] Built target test-c
[ 46%] Building CXX object common/CMakeFiles/common.dir/common.cpp.o
[ 46%] Building CXX object examples/simple/CMakeFiles/llama-simple.dir/simple.cpp.o
[ 46%] Linking CXX executable ../../bin/llama-simple
[ 46%] Built target llama-simple
[ 47%] Building CXX object examples/simple-chat/CMakeFiles/llama-simple-chat.dir/simple-chat.cpp.o
[ 47%] Linking CXX executable ../../bin/llama-simple-chat
[ 47%] Built target llama-simple-chat
[ 47%] Building CXX object common/CMakeFiles/common.dir/console.cpp.o
[ 48%] Building CXX object common/CMakeFiles/common.dir/debug.cpp.o
[ 48%] Building CXX object common/CMakeFiles/common.dir/download.cpp.o
[ 48%] Building CXX object common/CMakeFiles/common.dir/json-partial.cpp.o
[ 48%] Building CXX object common/CMakeFiles/common.dir/json-schema-to-grammar.cpp.o
[ 49%] Building CXX object common/CMakeFiles/common.dir/llguidance.cpp.o
[ 49%] Building CXX object common/CMakeFiles/common.dir/log.cpp.o
[ 49%] Building CXX object common/CMakeFiles/common.dir/ngram-cache.cpp.o
[ 49%] Building CXX object common/CMakeFiles/common.dir/ngram-map.cpp.o
[ 49%] Building CXX object common/CMakeFiles/common.dir/ngram-mod.cpp.o
[ 50%] Building CXX object common/CMakeFiles/common.dir/peg-parser.cpp.o
[ 50%] Building CXX object common/CMakeFiles/common.dir/preset.cpp.o

In [2]:

from pathlib import Path
import os

PROJECT_ROOT = Path('/content/drive/MyDrive/Week8')
ADAPTER_DIR = PROJECT_ROOT / 'adapters'
QUANT_DIR = PROJECT_ROOT / 'quantized'
MERGED_DIR = PROJECT_ROOT / 'models' / 'merged_fp16'
REPORT_JSON = PROJECT_ROOT / 'quantized' / 'quantization_summary.json'

INT8_DIR = QUANT_DIR / 'model-int8'
INT4_DIR = QUANT_DIR / 'model-int4'
GGUF_PATH = QUANT_DIR / 'model.gguf'
GGUF_F16_PATH = QUANT_DIR / 'model-f16.gguf'

for p in [QUANT_DIR, MERGED_DIR, INT8_DIR, INT4_DIR]:
    p.mkdir(parents=True, exist_ok=True)

print('ADAPTER_DIR :', ADAPTER_DIR)
print('MERGED_DIR  :', MERGED_DIR)
print('INT8_DIR    :', INT8_DIR)
print('INT4_DIR    :', INT4_DIR)
print('GGUF_PATH   :', GGUF_PATH)

ADAPTER_DIR : /content/drive/MyDrive/Week8/adapters
MERGED_DIR  : /content/drive/MyDrive/Week8/models/merged_fp16
INT8_DIR    : /content/drive/MyDrive/Week8/quantized/model-int8
INT4_DIR    : /content/drive/MyDrive/Week8/quantized/model-int4
GGUF_PATH   : /content/drive/MyDrive/Week8/quantized/model.gguf

In [3]:

required = [
    ADAPTER_DIR / 'adapter_model.bin',
    ADAPTER_DIR / 'adapter_config.json',
]
for p in required:
    print(p, '->', p.exists())

/content/drive/MyDrive/Week8/adapters/adapter_model.bin -> True
/content/drive/MyDrive/Week8/adapters/adapter_config.json -> True

In [6]:
# 6) Imports and config
import json
import time
import shutil
import subprocess
import pandas as pd
import torch

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
)
from peft import PeftModel

BASE_MODEL_NAME = 'TinyLlama/TinyLlama-1.1B-Chat-v1.0'
TEST_PROMPTS = [
    "### Instruction:\nAnswer this medical question.\n\n### Input:\nWhat is pneumonia?\n\n### Response:\n",
    "### Instruction:\nReason briefly and answer.\n\n### Input:\nA patient has unilateral leg swelling after a long flight and sudden neurological deficits. What cardiac finding may explain this?\n\n### Response:\n",
]

print('Torch version:', torch.__version__)
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

Torch version: 2.10.0+cu128
CUDA available: True
GPU: Tesla T4

In [7]:
# 7) Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_NAME, use_fast=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = 'left'
print('Tokenizer loaded.')

Tokenizer loaded.

In [8]:
# 8) Load base FP16 model
base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL_NAME,
    torch_dtype=torch.float16,
    device_map='auto',
)

peft_model = PeftModel.from_pretrained(base_model, str(ADAPTER_DIR))
merged_model = peft_model.merge_and_unload()

merged_model.save_pretrained(str(MERGED_DIR), safe_serialization=True)
tokenizer.save_pretrained(str(MERGED_DIR))

print('Merged model saved to:', MERGED_DIR)

`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Merged model saved to: /content/drive/MyDrive/Week8/models/merged_fp16

In [9]:
# 9) Load and save 8-bit model
bnb_int8 = BitsAndBytesConfig(load_in_8bit=True)

model_int8 = AutoModelForCausalLM.from_pretrained(
    str(MERGED_DIR),
    quantization_config=bnb_int8,
    device_map='auto',
)

model_int8.save_pretrained(str(INT8_DIR), safe_serialization=True)
tokenizer.save_pretrained(str(INT8_DIR))

print('Saved INT8 model to:', INT8_DIR)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Saved INT8 model to: /content/drive/MyDrive/Week8/quantized/model-int8

In [10]:
# 10) Load and save 4-bit model
bnb_int4 = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16,
)

model_int4 = AutoModelForCausalLM.from_pretrained(
    str(MERGED_DIR),
    quantization_config=bnb_int4,
    device_map='auto',
)

model_int4.save_pretrained(str(INT4_DIR), safe_serialization=True)
tokenizer.save_pretrained(str(INT4_DIR))

print('Saved INT4 model to:', INT4_DIR)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Saved INT4 model to: /content/drive/MyDrive/Week8/quantized/model-int4

In [11]:
# 11) Convert merged model to GGUF (F16 first, then quantize to q4_0)
%cd /content/llama.cpp

!python convert_hf_to_gguf.py "{MERGED_DIR}" --outfile "{GGUF_F16_PATH}" --outtype f16
!./build/bin/llama-quantize "{GGUF_F16_PATH}" "{GGUF_PATH}" q4_0

print('Saved GGUF model to:', GGUF_PATH)

/content/llama.cpp
INFO:hf-to-gguf:Loading model: merged_fp16
INFO:hf-to-gguf:Model architecture: LlamaForCausalLM
INFO:hf-to-gguf:gguf: indexing model part 'model.safetensors'
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Exporting model...
INFO:hf-to-gguf:output.weight,               torch.float16 --> F16, shape = {2048, 32000}
INFO:hf-to-gguf:token_embd.weight,           torch.float16 --> F16, shape = {2048, 32000}
INFO:hf-to-gguf:blk.0.attn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.0.ffn_down.weight,       torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.0.ffn_gate.weight,       torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.0.ffn_up.weight,         torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.0.ffn_norm.weight,       torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.0.attn_k.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.0.attn_output.weight,    torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.0.attn_q.weight,         torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.0.attn_v.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.1.attn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.1.ffn_down.weight,       torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.1.ffn_gate.weight,       torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.1.ffn_up.weight,         torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.1.ffn_norm.weight,       torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.1.attn_k.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.1.attn_output.weight,    torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.1.attn_q.weight,         torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.1.attn_v.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.10.attn_norm.weight,     torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.10.ffn_down.weight,      torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.10.ffn_gate.weight,      torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.10.ffn_up.weight,        torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.10.ffn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.10.attn_k.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.10.attn_output.weight,   torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.10.attn_q.weight,        torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.10.attn_v.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.11.attn_norm.weight,     torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.11.ffn_down.weight,      torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.11.ffn_gate.weight,      torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.11.ffn_up.weight,        torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.11.ffn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.11.attn_k.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.11.attn_output.weight,   torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.11.attn_q.weight,        torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.11.attn_v.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.12.attn_norm.weight,     torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.12.ffn_down.weight,      torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.12.ffn_gate.weight,      torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.12.ffn_up.weight,        torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.12.ffn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.12.attn_k.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.12.attn_output.weight,   torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.12.attn_q.weight,        torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.12.attn_v.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.13.attn_norm.weight,     torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.13.ffn_down.weight,      torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.13.ffn_gate.weight,      torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.13.ffn_up.weight,        torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.13.ffn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.13.attn_k.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.13.attn_output.weight,   torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.13.attn_q.weight,        torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.13.attn_v.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.14.attn_norm.weight,     torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.14.ffn_down.weight,      torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.14.ffn_gate.weight,      torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.14.ffn_up.weight,        torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.14.ffn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.14.attn_k.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.14.attn_output.weight,   torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.14.attn_q.weight,        torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.14.attn_v.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.15.attn_norm.weight,     torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.15.ffn_down.weight,      torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.15.ffn_gate.weight,      torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.15.ffn_up.weight,        torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.15.ffn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.15.attn_k.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.15.attn_output.weight,   torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.15.attn_q.weight,        torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.15.attn_v.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.16.attn_norm.weight,     torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.16.ffn_down.weight,      torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.16.ffn_gate.weight,      torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.16.ffn_up.weight,        torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.16.ffn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.16.attn_k.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.16.attn_output.weight,   torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.16.attn_q.weight,        torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.16.attn_v.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.17.attn_norm.weight,     torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.17.ffn_down.weight,      torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.17.ffn_gate.weight,      torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.17.ffn_up.weight,        torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.17.ffn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.17.attn_k.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.17.attn_output.weight,   torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.17.attn_q.weight,        torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.17.attn_v.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.18.attn_norm.weight,     torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.18.ffn_down.weight,      torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.18.ffn_gate.weight,      torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.18.ffn_up.weight,        torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.18.ffn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.18.attn_k.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.18.attn_output.weight,   torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.18.attn_q.weight,        torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.18.attn_v.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.19.attn_norm.weight,     torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.19.ffn_down.weight,      torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.19.ffn_gate.weight,      torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.19.ffn_up.weight,        torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.19.ffn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.19.attn_k.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.19.attn_output.weight,   torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.19.attn_q.weight,        torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.19.attn_v.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.2.attn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.2.ffn_down.weight,       torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.2.ffn_gate.weight,       torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.2.ffn_up.weight,         torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.2.ffn_norm.weight,       torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.2.attn_k.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.2.attn_output.weight,    torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.2.attn_q.weight,         torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.2.attn_v.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.20.attn_norm.weight,     torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.20.ffn_down.weight,      torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.20.ffn_gate.weight,      torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.20.ffn_up.weight,        torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.20.ffn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.20.attn_k.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.20.attn_output.weight,   torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.20.attn_q.weight,        torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.20.attn_v.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.21.attn_norm.weight,     torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.21.ffn_down.weight,      torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.21.ffn_gate.weight,      torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.21.ffn_up.weight,        torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.21.ffn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.21.attn_k.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.21.attn_output.weight,   torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.21.attn_q.weight,        torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.21.attn_v.weight,        torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.3.attn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.3.ffn_down.weight,       torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.3.ffn_gate.weight,       torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.3.ffn_up.weight,         torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.3.ffn_norm.weight,       torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.3.attn_k.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.3.attn_output.weight,    torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.3.attn_q.weight,         torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.3.attn_v.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.4.attn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.4.ffn_down.weight,       torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.4.ffn_gate.weight,       torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.4.ffn_up.weight,         torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.4.ffn_norm.weight,       torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.4.attn_k.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.4.attn_output.weight,    torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.4.attn_q.weight,         torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.4.attn_v.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.5.attn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.5.ffn_down.weight,       torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.5.ffn_gate.weight,       torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.5.ffn_up.weight,         torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.5.ffn_norm.weight,       torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.5.attn_k.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.5.attn_output.weight,    torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.5.attn_q.weight,         torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.5.attn_v.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.6.attn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.6.ffn_down.weight,       torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.6.ffn_gate.weight,       torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.6.ffn_up.weight,         torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.6.ffn_norm.weight,       torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.6.attn_k.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.6.attn_output.weight,    torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.6.attn_q.weight,         torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.6.attn_v.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.7.attn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.7.ffn_down.weight,       torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.7.ffn_gate.weight,       torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.7.ffn_up.weight,         torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.7.ffn_norm.weight,       torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.7.attn_k.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.7.attn_output.weight,    torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.7.attn_q.weight,         torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.7.attn_v.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.8.attn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.8.ffn_down.weight,       torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.8.ffn_gate.weight,       torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.8.ffn_up.weight,         torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.8.ffn_norm.weight,       torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.8.attn_k.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.8.attn_output.weight,    torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.8.attn_q.weight,         torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.8.attn_v.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.9.attn_norm.weight,      torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.9.ffn_down.weight,       torch.float16 --> F16, shape = {5632, 2048}
INFO:hf-to-gguf:blk.9.ffn_gate.weight,       torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.9.ffn_up.weight,         torch.float16 --> F16, shape = {2048, 5632}
INFO:hf-to-gguf:blk.9.ffn_norm.weight,       torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:blk.9.attn_k.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:blk.9.attn_output.weight,    torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.9.attn_q.weight,         torch.float16 --> F16, shape = {2048, 2048}
INFO:hf-to-gguf:blk.9.attn_v.weight,         torch.float16 --> F16, shape = {2048, 256}
INFO:hf-to-gguf:output_norm.weight,          torch.float16 --> F32, shape = {2048}
INFO:hf-to-gguf:Set meta model
INFO:hf-to-gguf:Set model parameters
INFO:hf-to-gguf:gguf: context length = 2048
INFO:hf-to-gguf:gguf: embedding length = 2048
INFO:hf-to-gguf:gguf: feed forward length = 5632
INFO:hf-to-gguf:gguf: head count = 32
INFO:hf-to-gguf:gguf: key-value head count = 4
WARNING:hf-to-gguf:Unknown RoPE type: default
INFO:hf-to-gguf:gguf: rope scaling type = NONE
INFO:hf-to-gguf:gguf: rope theta = 10000.0
INFO:hf-to-gguf:gguf: rms norm epsilon = 1e-05
INFO:hf-to-gguf:gguf: file type = 1
INFO:hf-to-gguf:Set model quantization version
INFO:hf-to-gguf:Set model tokenizer
INFO:numexpr.utils:NumExpr defaulting to 2 threads.
WARNING:gguf.vocab:Unknown separator token '<s>' in TemplateProcessing<pair>
INFO:gguf.vocab:Setting special token type bos to 1
INFO:gguf.vocab:Setting special token type eos to 2
INFO:gguf.vocab:Setting special token type unk to 0
INFO:gguf.vocab:Setting special token type pad to 2
INFO:gguf.vocab:Setting add_bos_token to True
INFO:gguf.vocab:Setting add_sep_token to False
INFO:gguf.vocab:Setting chat_template to {% for message in messages %}
{% if message['role'] == 'user' %}
{{ '<|user|>
' + message['content'] + eos_token }}
{% elif message['role'] == 'system' %}
{{ '<|system|>
' + message['content'] + eos_token }}
{% elif message['role'] == 'assistant' %}
{{ '<|assistant|>
'  + message['content'] + eos_token }}
{% endif %}
{% if loop.last and add_generation_prompt %}
{{ '<|assistant|>' }}
{% endif %}
{% endfor %}
INFO:gguf.gguf_writer:Writing the following files:
INFO:gguf.gguf_writer:/content/drive/MyDrive/Week8/quantized/model-f16.gguf: n_tensors = 201, total_size = 2.2G
Writing: 100% 2.20G/2.20G [00:25<00:00, 85.4Mbyte/s]
INFO:hf-to-gguf:Model successfully exported to /content/drive/MyDrive/Week8/quantized/model-f16.gguf
main: build = 8427 (512bba6ee)
main: built with GNU 11.4.0 for Linux x86_64
main: quantizing '/content/drive/MyDrive/Week8/quantized/model-f16.gguf' to '/content/drive/MyDrive/Week8/quantized/model.gguf' as Q4_0

In [12]:
# 12) Utility: get directory/file sizes
def get_size_mb(path: Path) -> float:
    if path.is_file():
        return path.stat().st_size / (1024 ** 2)
    total = 0
    for root, _, files in os.walk(path):
        for f in files:
            total += os.path.getsize(os.path.join(root, f))
    return total / (1024 ** 2)

sizes = {
    'FP16_merged_mb': get_size_mb(MERGED_DIR),
    'INT8_mb': get_size_mb(INT8_DIR),
    'INT4_mb': get_size_mb(INT4_DIR),
    'GGUF_q4_0_mb': get_size_mb(GGUF_PATH),
}
sizes

{'FP16_merged_mb': 2101.6503896713257,
 'INT8_mb': 1179.185625076294,
 'INT4_mb': 730.5854063034058,
 'GGUF_q4_0_mb': 607.2297973632812}

In [13]:
# 13) Quick HF generation benchmark helper
def benchmark_hf_model(model, tokenizer, prompt, max_new_tokens=80):
    inputs = tokenizer(prompt, return_tensors='pt').to(model.device)
    start = time.time()
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            temperature=0.0,
            pad_token_id=tokenizer.eos_token_id,
        )
    elapsed = time.time() - start
    generated = outputs[0][inputs['input_ids'].shape[1]:]
    num_tokens = generated.shape[0]
    text = tokenizer.decode(generated, skip_special_tokens=True)
    return {
        'seconds': round(elapsed, 4),
        'new_tokens': int(num_tokens),
        'tokens_per_sec': round(num_tokens / max(elapsed, 1e-6), 4),
        'text': text,
    }

In [14]:
# 14) Run quick quality + speed check for FP16 / INT8 / INT4
records = []

# reload small references cleanly
model_fp16 = AutoModelForCausalLM.from_pretrained(str(MERGED_DIR), torch_dtype=torch.float16, device_map='auto')
model_int8_eval = AutoModelForCausalLM.from_pretrained(str(INT8_DIR), device_map='auto')
model_int4_eval = AutoModelForCausalLM.from_pretrained(str(INT4_DIR), device_map='auto')

for prompt in TEST_PROMPTS:
    fp16_result = benchmark_hf_model(model_fp16, tokenizer, prompt)
    int8_result = benchmark_hf_model(model_int8_eval, tokenizer, prompt)
    int4_result = benchmark_hf_model(model_int4_eval, tokenizer, prompt)

    records.extend([
        {'format': 'FP16', 'prompt': prompt, **fp16_result},
        {'format': 'INT8', 'prompt': prompt, **int8_result},
        {'format': 'INT4', 'prompt': prompt, **int4_result},
    ])

hf_df = pd.DataFrame(records)
hf_df.head()

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Both `max_new_tokens` (=80) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=80) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=80) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=80) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=80) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=80) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=80) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=80) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=80) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

,format,prompt,seconds,new_tokens,tokens_per_sec,text
0,FP16,Explain the difference between bacterial and v...,3.5599,80,22.4723,\nSolve the medical reasoning problem carefull...
1,INT8,Explain the difference between bacterial and v...,8.9044,80,8.9843,\nSolve the medical reasoning problem carefull...
2,INT4,Explain the difference between bacterial and v...,0.1128,1,8.8674,
3,FP16,What is the likely diagnosis for sudden unilat...,2.5269,80,31.6597,\nAnswer: What is the likely diagnosis for sud...
4,INT8,What is the likely diagnosis for sudden unilat...,7.9301,80,10.0882,\nAnswer : What is the likely diagnosis for su...

In [9]:
from pathlib import Path
print(GGUF_PATH)
print(Path(GGUF_PATH).exists())
print(Path(GGUF_PATH).stat().st_size / (1024**3), "GB")

/content/drive/MyDrive/Week8/quantized/model.gguf
True
0.5929978489875793 GB

In [2]:
from pathlib import Path

quant_dir = Path("/content/drive/MyDrive/Week8/quantized")

paths = {
    "int8_dir": quant_dir / "model-int8",
    "int4_dir": quant_dir / "model-int4",
    "gguf_file": quant_dir / "model.gguf",
}

for name, path in paths.items():
    print(name, "->", path.exists(), path)
    if path.exists() and path.is_file():
        print("  size_gb:", round(path.stat().st_size / (1024**3), 4))

int8_dir -> True /content/drive/MyDrive/Week8/quantized/model-int8
int4_dir -> True /content/drive/MyDrive/Week8/quantized/model-int4
gguf_file -> True /content/drive/MyDrive/Week8/quantized/model.gguf
  size_gb: 0.593

In [3]:
import os
import json
import pandas as pd
from pathlib import Path

quant_dir = Path("/content/drive/MyDrive/Week8/quantized")
records = []

items = [
    ("INT8", quant_dir / "model-int8"),
    ("INT4", quant_dir / "model-int4"),
    ("GGUF_q4_0", quant_dir / "model.gguf"),
]

for label, path in items:
    if path.exists():
        if path.is_file():
            size_bytes = path.stat().st_size
        else:
            size_bytes = 0
            for root, _, files in os.walk(path):
                for f in files:
                    fp = Path(root) / f
                    if fp.exists():
                        size_bytes += fp.stat().st_size

        records.append({
            "format": label,
            "path": str(path),
            "exists": True,
            "size_mb": round(size_bytes / (1024**2), 2),
            "size_gb": round(size_bytes / (1024**3), 4),
            "status": "generated"
        })
    else:
        records.append({
            "format": label,
            "path": str(path),
            "exists": False,
            "size_mb": None,
            "size_gb": None,
            "status": "missing"
        })

df = pd.DataFrame(records)
df

,format,path,exists,size_mb,size_gb,status
0,INT8,/content/drive/MyDrive/Week8/quantized/model-int8,True,1179.19,1.1515,generated
1,INT4,/content/drive/MyDrive/Week8/quantized/model-int4,True,730.59,0.7135,generated
2,GGUF_q4_0,/content/drive/MyDrive/Week8/quantized/model.gguf,True,607.23,0.5930,generated

In [4]:
out_csv = quant_dir / "quantization_summary.csv"
out_json = quant_dir / "quantization_summary.json"

df.to_csv(out_csv, index=False)
df.to_json(out_json, orient="records", indent=2)

print("Saved:", out_csv)
print("Saved:", out_json)

Saved: /content/drive/MyDrive/Week8/quantized/quantization_summary.csv
Saved: /content/drive/MyDrive/Week8/quantized/quantization_summary.json